sudo : true
dist : trusty
language: node_js
node_js:
  - "node"
addons:
  sauce_connect: true
  ssh_known_hosts: download.kiwix.org
before_script:
    - npm install nightwatch http-server
    - "./node_modules/http-server/bin/http-server . &"
script:
    # The free account on Sauce does not allow more than 5 concurrent sessions (including the main one)
    # So we separate the recent and old browsers in order to respect this limit.
    # NB : latest edge should be added to this list when Microsoft releases the new Edge based on Chromium
    - "./node_modules/nightwatch/bin/nightwatch -c nightwatch.js --env firefox,chrome"
    - "./node_modules/nightwatch/bin/nightwatch -c nightwatch.js --env edge40,edge44"
    - "./node_modules/nightwatch/bin/nightwatch -c nightwatch.js --env firefox45,chrome58,ie11"
    - pkill node || echo "Node process not running (anymore)"
